// AUTH

export const AUTO_LOGIN = "AUTO_LOGIN";
export const AUTO_LOGIN_BEGIN = "AUTO_LOGIN_BEGIN";
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS";
export const AUTO_LOGIN_FAILURE = "AUTO_LOGIN_FAILURE";
export const AUTO_LOGIN_RESET = "AUTO_LOGIN_RESET";
